In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display settings
pd.set_option("display.max_columns", None)

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [2]:
# LOAD DATASETS

In [3]:
products_df = pd.read_csv("../data/products.csv")

customers_df = pd.read_csv("../data/customers.csv")

orders_df = pd.read_csv("../data/orders.csv")

returns_df = pd.read_csv("../data/returns.csv")

print("Datasets loaded successfully.")

Datasets loaded successfully.

In [4]:
# INITIAL DATA INSPECTION

In [5]:
print("Products Shape:", products_df.shape)

print("Customers Shape:", customers_df.shape)

print("Orders Shape:", orders_df.shape)

print("Returns Shape:", returns_df.shape)

Products Shape: (705, 7)
Customers Shape: (20015, 8)
Orders Shape: (50050, 16)
Returns Shape: (6637, 5)

In [6]:
orders_df.head()

,Order_ID,Order_Date,Ship_Date,Customer_ID,Product_ID,Region,State,City,Segment,Sales_Channel,Sales,Quantity,Discount,Profit,Ship_Mode,Payment_Mode
0,ORD-500001,2024-08-16,2024-08-18,CUST-13649,PRD-10479,North,Punjab,Ludhiana,Consumer,Online,39978.96,3,0.13,2801.81,Express,Credit Card
1,ORD-500002,2025-10-27,2025-11-03,CUST-17624,PRD-10366,North,Rajasthan,Bikaner,Premium,Offline,60060.06,3,0.26,-7864.88,Economy,Debit Card
2,ORD-500003,2024-04-04,2024-04-10,CUST-15095,PRD-10342,South,Telangana,Hyderabad,Premium,Marketplace,1172.04,3,0.10,-641.77,Economy,UPI
3,ORD-500004,2025-08-14,2025-08-16,CUST-22404,PRD-10009,North,Punjab,Amritsar,Corporate,Online,2546.44,1,0.17,157.50,Express,Net Banking
4,ORD-500005,2024-06-15,2024-06-20,CUST-19109,PRD-10692,East,Assam,Guwahati,Corporate,Online,121487.36,2,0.08,13983.16,Same Day,Net Banking

In [7]:
# DATA TYPES

In [8]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50050 entries, 0 to 50049
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       50050 non-null  object
 1   Order_Date     50050 non-null  object
 2   Ship_Date      49541 non-null  object
 3   Customer_ID    50050 non-null  object
 4   Product_ID     50050 non-null  object
 5   Region         50050 non-null  object
 6   State          50050 non-null  object
 7   City           50050 non-null  object
 8   Segment        50050 non-null  object
 9   Sales_Channel  50050 non-null  object
 10  Sales          50050 non-null  float64
 11  Quantity       50050 non-null  int64
 12  Discount       49548 non-null  float64
 13  Profit         50050 non-null  float64
 14  Ship_Mode      50050 non-null  object
 15  Payment_Mode   50050 non-null  object
dtypes: float64(3), int64(1), object(12)
memory usage: 3.8+ MB

In [9]:
# MISSING VALUES

In [10]:
print("\nMissing Values - Orders")

print(orders_df.isnull().sum())

print("\nMissing Values - Customers")

print(customers_df.isnull().sum())

Missing Values - Orders
Order_ID           0
Order_Date         0
Ship_Date        509
Customer_ID        0
Product_ID         0
Region             0
State              0
City               0
Segment            0
Sales_Channel      0
Sales              0
Quantity           0
Discount         502
Profit             0
Ship_Mode          0
Payment_Mode       0
dtype: int64

Missing Values - Customers
Customer_ID              0
Customer_Name            0
Age_Group              305
Gender                   0
City                     0
Join_Date                0
Loyalty_Status           0
Acquisition_Channel    246
dtype: int64

In [11]:
# DUPLICATE VALUES

In [12]:
print("Duplicate Orders:",
      orders_df.duplicated().sum())

print("Duplicate Customers:",
      customers_df.duplicated().sum())

Duplicate Orders: 50
Duplicate Customers: 15

In [13]:
# BASIC CLEANING

In [14]:
# Remove Duplicates

orders_df = orders_df.drop_duplicates()

customers_df = customers_df.drop_duplicates()

products_df = products_df.drop_duplicates()

returns_df = returns_df.drop_duplicates()

print("Duplicates removed.")

Duplicates removed.

In [15]:
# Convert Dates

orders_df["Order_Date"] = pd.to_datetime(
    orders_df["Order_Date"],
    errors="coerce"
)

orders_df["Ship_Date"] = pd.to_datetime(
    orders_df["Ship_Date"],
    errors="coerce"
)

customers_df["Join_Date"] = pd.to_datetime(
    customers_df["Join_Date"],
    errors="coerce"
)

print("Date conversion completed.")

Date conversion completed.

In [16]:
# Fill Missing Discounts

orders_df["Discount"] = (
    orders_df["Discount"]
    .fillna(0)
)

In [17]:
# DERIVED METRICS

In [18]:
# Shipping Days
orders_df["Shipping_Days"] = (
    orders_df["Ship_Date"]
    - orders_df["Order_Date"]
).dt.days

# Profit Margin %
orders_df["Profit_Margin_Percent"] = (
    orders_df["Profit"]
    / orders_df["Sales"]
) * 100

In [19]:
# MASTER ANALYTICS DATAFRAME

In [20]:
# =====================================================
# MERGE DATASETS
# =====================================================

master_df = orders_df.merge(
    customers_df,
    on="Customer_ID",
    how="left"
)

master_df = master_df.merge(
    products_df,
    on="Product_ID",
    how="left"
)

master_df = master_df.merge(
    returns_df,
    on="Order_ID",
    how="left"
)

print("Master DataFrame created successfully.")

Master DataFrame created successfully.

In [21]:
# Validate Master Dataframe

In [22]:
print(master_df.shape)
master_df.head()

(50026, 35)

,Order_ID,Order_Date,Ship_Date,Customer_ID,Product_ID,Region,State,City_x,Segment,Sales_Channel,Sales,Quantity,Discount,Profit,Ship_Mode,Payment_Mode,Shipping_Days,Profit_Margin_Percent,Customer_Name,Age_Group,Gender,City_y,Join_Date,Loyalty_Status,Acquisition_Channel,Product_Name,Category,Sub_Category,Supplier,Manufacturing_Cost,Retail_Price,Return_ID,Return_Reason,Refund_Amount,Return_Status
0,ORD-500001,2024-08-16,2024-08-18,CUST-13649,PRD-10479,North,Punjab,Ludhiana,Consumer,Online,39978.96,3,0.13,2801.81,Express,Credit Card,2.0,7.008211,Xavier Chatterjee,36-45,Female,Ahmedabad,2022-04-28,Bronze,Referral,Canvas Art 491,Home Decor,Wall Art,Aura Living,10522.68,13326.32,NaN,NaN,NaN,NaN
1,ORD-500002,2025-10-27,2025-11-03,CUST-17624,PRD-10366,North,Rajasthan,Bikaner,Premium,Offline,60060.06,3,0.26,-7864.88,Economy,Debit Card,7.0,-13.095025,William Minhas,18-25,Female,Ahmedabad,2021-09-10,Platinum,Marketplace,Nova 988,Electronics,Mobile Phones,Nova Imports,17319.93,20020.02,RET-10001,Size Issue,52547.03,Approved
2,ORD-500003,2024-04-04,2024-04-10,CUST-15095,PRD-10342,South,Telangana,Hyderabad,Premium,Marketplace,1172.04,3,0.10,-641.77,Economy,UPI,6.0,-54.756664,Joshua Dass,18-25,Male,Hyderabad,2022-09-28,Silver,Instagram Ads,Organic Mix 526,Grocery,Packaged Food,PrimeGrocers Ltd,358.36,390.68,NaN,NaN,NaN,NaN
3,ORD-500004,2025-08-14,2025-08-16,CUST-22404,PRD-10009,North,Punjab,Amritsar,Corporate,Online,2546.44,1,0.17,157.50,Express,Net Banking,2.0,6.185105,Ikshita Kapoor,18-25,Male,Bengaluru,2025-11-06,Silver,Google Ads,Top 818,Fashion,Women Clothing,TrendHive India,1660.36,2546.44,NaN,NaN,NaN,NaN
4,ORD-500005,2024-06-15,2024-06-20,CUST-19109,PRD-10692,East,Assam,Guwahati,Corporate,Online,121487.36,2,0.08,13983.16,Same Day,Net Banking,5.0,11.509971,Rohan Prashad,36-45,Male,Bengaluru,2022-06-25,Bronze,Instagram Ads,Recliner 104,Furniture,Sofas,WoodCraft India,48531.79,60743.68,RET-10002,Defective Product,120289.84,Approved